
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftTIMESleftPLUSLPAREN NUMBER PLUS RPAREN TIMESexpression : expression PLUS expression expression : term\n                       | factor\n        expression : expression TIMES expressionterm : factorfactor : NUMBERfactor : LPAREN expression RPAREN'
    
_lr_action_items = {'NUMBER':([0,5,6,7,],[4,4,4,4,]),'LPAREN':([0,5,6,7,],[5,5,5,5,]),'$end':([1,2,3,4,9,10,11,],[0,-2,-3,-6,-1,-4,-7,]),'PLUS':([1,2,3,4,8,9,10,11,],[6,-2,-3,-6,6,-1,6,-7,]),'TIMES':([1,2,3,4,8,9,10,11,],[7,-2,-3,-6,7,-1,-4,-7,]),'RPAREN':([2,3,4,8,9,10,11,],[-2,-3,-6,11,-1,-4,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,5,6,7,],[1,8,9,10,]),'term':([0,5,6,7,],[2,2,2,2,]),'factor':([0,5,6,7,],[3,3,3,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS expression','expression',3,'p_expression_plus','day18.py',54),
  ('expression -> term','expression',1,'p_expression_term','day18.py',58),
  ('expression -> factor','expression',1,'p_expression_term','day18.py',59),
  ('expression -> expression TIMES expression','expression',3,'p_term_times','day18.py',64),
  ('term -> factor','term',1,'p_term_factor','day18.py',68),
  ('factor -> NUMBER','factor',1,'p_factor_num','day18.py',72),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expr','day18.py',76),
]
